### ISSUE TITLE
подрубить ci

### ISSUE THREAD

**Issue by kurumoch** [KurumochTeam/QuizApp#2]
travis ci мб

**Comment by SaNiK3D** [comment]
куда ты хочешь ci собирать? У нас даже нет акка с сертификатами

**Comment by kurumoch** [comment]
разберемся

**Comment by SaNiK3D** [comment]
пока это ненужная таска, как мне кажется, Рано еще об этом думать, Предлагаю закрыть

**Comment by kurumoch** [comment]
я в этом поковыряться хочу
как проект создадите, разберусь

**Comment by SaNiK3D** [comment]
Так как ты сборки будешь без сертификата собирать?

**Comment by kurumoch** [comment]
я же говорю, что не знаю

**Comment by SaNiK3D** [comment]
Нужно добавить подтягивание либ чере Carthage
